version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

    commands:
      #install npm
      - yarn install

  build:
    commands:
      # run build command
      - yarn run build

artifacts:
  # include the files required to run application
  files:
    - dist/**/*
    - backend-dist/**/*
    - scripts/**/*
    - appspec.yml